collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6772288
color:
  saturation: 0
  brandStrength: 0.537594
  lightness: 0.9350161
  brandColors:
    - '#342B22'
    - '#88A8D9'
    - '#FAEAD1'
    - '#525252'
    - '#0C0C0C'
  rhythmicContrast: 0.1015037
layout_spectrum: 0.5859291
name: Svenssons
