layout_spectrum: 0.5859291
color:
  saturation: 0.7577873
  lightness: 0.7287863
  brandStrength: 0.537594
  brandColors:
    - '#342B22'
    - '#88A8D9'
    - '#FAEAD1'
    - '#525252'
    - '#0C0C0C'
  rhythmicContrast: 0.6288937
typography_spectrum: 0.6772288
name: Svenssons
